global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['localhost:5000']  # Replace with your actual host/port if remote
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
